# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3f81a774fd82d6b2e6a386aafcc2d59ec8acf4bb4839403f3a49800c79f1533bf6f833162ca9fe4a485a3341a797105b35154b8e3d383b875a7053112cf3ced

test:
  secret_key_base: 59f1f042b627b8989d4ad529c1f3bc64f89abb7cff8eb893babb917ecb70e6fa5e81c4977e53edba901c7fde07195a49250d19d574a734c9fa691725b25d64b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
